config/routes.rb
Rails.application.routes.draw do
    ### get 'URL' => 'ControllerName#ActionName'
# Home
  root 'static_pages#home'
  get 'static_pages/help' => 'static_pages#help', as: :help
  get 'static_pages/about' => 'static_pages#about', as: :about
  
# Topics
  get 'topics/index'
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topics_delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
#Applicationcontrollerクラスを継承することで、クラスがコントローラと認識される

class PostsController < ApplicationController
    def index
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @newTopic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
  end

  # Topicの新規作成
  def create
    @topic = Topic.new(params[:topic].permit(:title))
    @topic.save
    redirect_to topics_index_path
  end

  # Topicの消去
  def delete
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Hello World</h1>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/topics/index.html.erb
<% provide(:button_text, 'Create Topic') %>

<h1>トピック一覧</h1>
<ul>
    <% @topics.each do |topic| %>
        <li>
            <%= link_to topic.title, topics_show_path(topic.id) %>
            <%= link_to "削除", topics_delete_path(topic.id),
            method: :delete, data: {confirm: "削除してもよろしいですか？"} , class:"btn btn-primary" %>
        </li>
    <% end %>
</ul>

<h1>トピック新規作成</h1>
<%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
    <%= f.text_field :title %>
    <%= f.submit yield(:button_text), class:"btn btn-primary" %>
<% end %>



<a class="btn btn-primary" href="#" role="button">Link</a>
<button class="btn btn-primary" type="submit">Button</button>
<input class="btn btn-primary" type="button" value="Input">
<input class="btn btn-primary" type="submit" value="Submit">
<input class="btn btn-primary" type="reset" value="Reset">

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>

<h1>トピック内容</h1>
    <p>
        <%= @topic.title %>
    </p>